readme: guessinggame.sh
	touch README.md
	echo "# Guessing project" >> README.md
	echo "" >> README.md
	echo "" >> README.md
	echo "The title of the project: Guessing" >> README.md
	echo "" >> README.md
	echo "The date and time at which make was run: $(shell date)" >> README.md
	echo "" >> README.md
	echo "The number of lines of code contained in guessinggame.sh: $(shell cat guessinggame.sh | wc -l)" >> README.md

clean:
	rm README.md
